### ISSUE TITLE
Reference Target Tracking Issue

### ISSUE THREAD

**Issue by dandclark** [WICG/webcomponents#1086]
Filing this issue as a central place to track open questions about [reference target](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/reference-target-explainer.md).

Blocking [Phase 1](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/reference-target-explainer.md#phase-1):
- [x]  https://github.com/WICG/webcomponents/issues/1071
- [x] https://github.com/WICG/webcomponents/issues/1072
- [x] https://github.com/WICG/webcomponents/issues/1087
- [x] https://github.com/WICG/webcomponents/issues/1093
- [ ] https://github.com/WICG/webcomponents/issues/1089
- [ ] https://github.com/WICG/webcomponents/issues/1091
- [ ]  https://github.com/WICG/webcomponents/issues/1098

Blocking [Phase 2](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/reference-target-explainer.md#-phase-2-shadowroot-referencetargetmap-attribute):
- [ ] An issue still needs to be filed on this, but we received feedback at [TPAC](https://github.com/w3c/tpac2024-breakouts/issues/30#issuecomment-2375176236) and from the TAG that the microsyntax proposed for phase 2 is undesirable. We should reconsider using separate attributes for each property to be redirected.
- [ ] In phase 2, how can an author indicate that references for a given property should [not be forwarded](https://github.com/w3ctag/design-reviews/issues/961#issuecomment-2468788538)?

Non-blocking:
- [ ] Depending on the outcome of https://github.com/w3ctag/gaps/issues/2, should something in addition to IDRefs be supported?

For Chromium implementation TODOs, see [here](https://issues.chromium.org/issues?q=id:346835896%20OR%20parentid:346835896%2B).

See also https://github.com/whatwg/html/issues/10707.

**Comment by Westbrook** [comment]
As of 2024Q4, the following tasks are NOT blocking an initial release, right?
- [ ] An issue still needs to be filed on this, but we received feedback at https://github.com/w3c/tpac2024-breakouts/issues/30#issuecomment-2375176236 and from the TAG that the microsyntax proposed for phase 2 is undesirable. We should reconsider using separate attributes for each property to be redirected.
- [ ] In phase 2, how can an author indicate that references for a given property should https://github.com/w3ctag/design-reviews/issues/961#issuecomment-2468788538?
- [ ] Depending on the outcome of https://github.com/w3ctag/gaps/issues/2, should something in addition to IDRefs be supported?
Each of these being "Phase 2"-centric.

**Comment by dandclark** [comment]
> As of 2024Q4, the following tasks are NOT blocking an initial release, right?

Right. I've edited the original comment to make this clearer.

**Comment by alice** [comment]
I filed an issue for the name bikeshed: https://github.com/WICG/webcomponents/issues/1087

**Comment by alice** [comment]
Apologies if I missed an earlier resolution on these issues, but I have come across some other potential blockers for phase 1.

- [ ] #1089 
- [ ] #1091

**Comment by alice** [comment]
- [ ] https://github.com/WICG/webcomponents/issues/1098
